/**
 * Auto-Generate Proposals and Invoices Service
 */

import { documentTemplateService } from './documentTemplates';

export interface ProposalConfig { customerName: string; projectType: 'solar' | 'wind' | 'battery' | 'hybrid'; systemSize: number; estimatedCost: number; items: Array<{ name: string; description: string; price: number }>; }
export interface InvoiceConfig { customerName: string; customerAddress: string; items: Array<{ description: string; quantity: number; unitPrice: number }>; dueDate?: Date; currency?: string; }
export interface GeneratedDocument { id: string; type: 'proposal' | 'invoice'; html: string; metadata: Record<string, any>; createdAt: Date; }

export class AutoGenerateDocumentsService {
  private counter = { proposal: 1000, invoice: 5000 };

  generateProposal(config: ProposalConfig): GeneratedDocument {
    const id = `PROP-${new Date().getFullYear()}-${++this.counter.proposal}`;
    const pricingItems = config.items.map(i => `<tr><td>${i.name}</td><td>${i.description}</td><td>$${i.price.toLocaleString()}</td></tr>`).join('');
    const html = documentTemplateService.render('proposal-standard', {
      proposalTitle: `${config.projectType.charAt(0).toUpperCase() + config.projectType.slice(1)} Energy System Proposal`,
      customerName: config.customerName,
      date: new Date().toLocaleDateString(),
      executiveSummary: `Proposal for a ${config.systemSize} kW ${config.projectType} system. Total investment: $${config.estimatedCost.toLocaleString()}.`,
      scopeOfWork: 'Site assessment, equipment procurement, installation, commissioning, and monitoring setup.',
      pricingItems,
      totalPrice: config.estimatedCost.toLocaleString(),
      currency: '$'
    }).html;
    return { id, type: 'proposal', html, metadata: { customerName: config.customerName, systemSize: config.systemSize }, createdAt: new Date() };
  }

  generateInvoice(config: InvoiceConfig): GeneratedDocument {
    const id = `INV-${new Date().getFullYear()}-${++this.counter.invoice}`;
    const currency = config.currency || '$';
    const items = config.items.map(i => ({ ...i, amount: i.quantity * i.unitPrice }));
    const total = items.reduce((s, i) => s + i.amount, 0);
    const lineItems = items.map(i => `<tr><td>${i.description}</td><td>${i.quantity}</td><td>${currency}${i.unitPrice.toFixed(2)}</td><td>${currency}${i.amount.toFixed(2)}</td></tr>`).join('');
    const dueDate = config.dueDate || new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);
    const html = documentTemplateService.render('invoice-standard', {
      companyName: 'KIISHA Energy',
      customerName: config.customerName,
      customerAddress: config.customerAddress,
      invoiceNumber: id,
      lineItems,
      total: total.toFixed(2),
      currency,
      dueDate: dueDate.toLocaleDateString()
    }).html;
    return { id, type: 'invoice', html, metadata: { customerName: config.customerName, total, dueDate }, createdAt: new Date() };
  }

  generateFromProject(project: any): GeneratedDocument {
    return this.generateProposal({
      customerName: project.customerName || 'Customer',
      projectType: project.type || 'solar',
      systemSize: project.capacity || 100,
      estimatedCost: project.estimatedCost || project.capacity * 1000,
      items: project.items || [
        { name: 'Equipment', description: 'Panels, inverters, mounting', price: project.capacity * 600 },
        { name: 'Installation', description: 'Labor and commissioning', price: project.capacity * 300 },
        { name: 'Permits', description: 'Permits and inspections', price: project.capacity * 100 }
      ]
    });
  }
}

export const autoGenerateDocumentsService = new AutoGenerateDocumentsService();
export default autoGenerateDocumentsService;
